// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.hxx

#ifndef PROTOBUF_common_2ehxx__INCLUDED
#define PROTOBUF_common_2ehxx__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_common_2ehxx();
void protobuf_InitDefaults_common_2ehxx();
void protobuf_AssignDesc_common_2ehxx();
void protobuf_ShutdownFile_common_2ehxx();

class PBItemEquip;
class PBItemList;
class PBItemObject;
class PBTask;
class PBTaskList;

// ===================================================================

class PBItemList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PBItemList) */ {
 public:
  PBItemList();
  virtual ~PBItemList();

  PBItemList(const PBItemList& from);

  inline PBItemList& operator=(const PBItemList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBItemList& default_instance();

  static const PBItemList* internal_default_instance();

  void Swap(PBItemList* other);

  // implements Message ----------------------------------------------

  inline PBItemList* New() const { return New(NULL); }

  PBItemList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBItemList& from);
  void MergeFrom(const PBItemList& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PBItemList* other);
  void UnsafeMergeFrom(const PBItemList& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .PBItemObject ItemObject = 1;
  int itemobject_size() const;
  void clear_itemobject();
  static const int kItemObjectFieldNumber = 1;
  const ::PBItemObject& itemobject(int index) const;
  ::PBItemObject* mutable_itemobject(int index);
  ::PBItemObject* add_itemobject();
  ::google::protobuf::RepeatedPtrField< ::PBItemObject >*
      mutable_itemobject();
  const ::google::protobuf::RepeatedPtrField< ::PBItemObject >&
      itemobject() const;

  // optional uint32 Size = 2;
  void clear_size();
  static const int kSizeFieldNumber = 2;
  ::google::protobuf::uint32 size() const;
  void set_size(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:PBItemList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::PBItemObject > itemobject_;
  ::google::protobuf::uint32 size_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_common_2ehxx_impl();
  friend void  protobuf_AddDesc_common_2ehxx_impl();
  friend void protobuf_AssignDesc_common_2ehxx();
  friend void protobuf_ShutdownFile_common_2ehxx();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<PBItemList> PBItemList_default_instance_;

// -------------------------------------------------------------------

class PBItemObject : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PBItemObject) */ {
 public:
  PBItemObject();
  virtual ~PBItemObject();

  PBItemObject(const PBItemObject& from);

  inline PBItemObject& operator=(const PBItemObject& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBItemObject& default_instance();

  static const PBItemObject* internal_default_instance();

  void Swap(PBItemObject* other);

  // implements Message ----------------------------------------------

  inline PBItemObject* New() const { return New(NULL); }

  PBItemObject* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBItemObject& from);
  void MergeFrom(const PBItemObject& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PBItemObject* other);
  void UnsafeMergeFrom(const PBItemObject& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 ItemID = 1;
  void clear_itemid();
  static const int kItemIDFieldNumber = 1;
  ::google::protobuf::uint32 itemid() const;
  void set_itemid(::google::protobuf::uint32 value);

  // optional uint32 Number = 2;
  void clear_number();
  static const int kNumberFieldNumber = 2;
  ::google::protobuf::uint32 number() const;
  void set_number(::google::protobuf::uint32 value);

  // optional uint32 Index = 3;
  void clear_index();
  static const int kIndexFieldNumber = 3;
  ::google::protobuf::uint32 index() const;
  void set_index(::google::protobuf::uint32 value);

  // optional .PBItemEquip ItemEquip = 4;
  bool has_itemequip() const;
  void clear_itemequip();
  static const int kItemEquipFieldNumber = 4;
  const ::PBItemEquip& itemequip() const;
  ::PBItemEquip* mutable_itemequip();
  ::PBItemEquip* release_itemequip();
  void set_allocated_itemequip(::PBItemEquip* itemequip);

  // @@protoc_insertion_point(class_scope:PBItemObject)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::PBItemEquip* itemequip_;
  ::google::protobuf::uint32 itemid_;
  ::google::protobuf::uint32 number_;
  ::google::protobuf::uint32 index_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_common_2ehxx_impl();
  friend void  protobuf_AddDesc_common_2ehxx_impl();
  friend void protobuf_AssignDesc_common_2ehxx();
  friend void protobuf_ShutdownFile_common_2ehxx();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<PBItemObject> PBItemObject_default_instance_;

// -------------------------------------------------------------------

class PBItemEquip : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PBItemEquip) */ {
 public:
  PBItemEquip();
  virtual ~PBItemEquip();

  PBItemEquip(const PBItemEquip& from);

  inline PBItemEquip& operator=(const PBItemEquip& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBItemEquip& default_instance();

  static const PBItemEquip* internal_default_instance();

  void Swap(PBItemEquip* other);

  // implements Message ----------------------------------------------

  inline PBItemEquip* New() const { return New(NULL); }

  PBItemEquip* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBItemEquip& from);
  void MergeFrom(const PBItemEquip& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PBItemEquip* other);
  void UnsafeMergeFrom(const PBItemEquip& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 Level = 4;
  void clear_level();
  static const int kLevelFieldNumber = 4;
  ::google::protobuf::uint32 level() const;
  void set_level(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:PBItemEquip)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 level_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_common_2ehxx_impl();
  friend void  protobuf_AddDesc_common_2ehxx_impl();
  friend void protobuf_AssignDesc_common_2ehxx();
  friend void protobuf_ShutdownFile_common_2ehxx();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<PBItemEquip> PBItemEquip_default_instance_;

// -------------------------------------------------------------------

class PBTask : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PBTask) */ {
 public:
  PBTask();
  virtual ~PBTask();

  PBTask(const PBTask& from);

  inline PBTask& operator=(const PBTask& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBTask& default_instance();

  static const PBTask* internal_default_instance();

  void Swap(PBTask* other);

  // implements Message ----------------------------------------------

  inline PBTask* New() const { return New(NULL); }

  PBTask* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBTask& from);
  void MergeFrom(const PBTask& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PBTask* other);
  void UnsafeMergeFrom(const PBTask& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 TaskID = 1;
  void clear_taskid();
  static const int kTaskIDFieldNumber = 1;
  ::google::protobuf::uint32 taskid() const;
  void set_taskid(::google::protobuf::uint32 value);

  // repeated uint32 Param = 2;
  int param_size() const;
  void clear_param();
  static const int kParamFieldNumber = 2;
  ::google::protobuf::uint32 param(int index) const;
  void set_param(int index, ::google::protobuf::uint32 value);
  void add_param(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      param() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_param();

  // repeated uint32 CondType = 3;
  int condtype_size() const;
  void clear_condtype();
  static const int kCondTypeFieldNumber = 3;
  ::google::protobuf::uint32 condtype(int index) const;
  void set_condtype(int index, ::google::protobuf::uint32 value);
  void add_condtype(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      condtype() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_condtype();

  // @@protoc_insertion_point(class_scope:PBTask)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > param_;
  mutable int _param_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > condtype_;
  mutable int _condtype_cached_byte_size_;
  ::google::protobuf::uint32 taskid_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_common_2ehxx_impl();
  friend void  protobuf_AddDesc_common_2ehxx_impl();
  friend void protobuf_AssignDesc_common_2ehxx();
  friend void protobuf_ShutdownFile_common_2ehxx();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<PBTask> PBTask_default_instance_;

// -------------------------------------------------------------------

class PBTaskList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PBTaskList) */ {
 public:
  PBTaskList();
  virtual ~PBTaskList();

  PBTaskList(const PBTaskList& from);

  inline PBTaskList& operator=(const PBTaskList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBTaskList& default_instance();

  static const PBTaskList* internal_default_instance();

  void Swap(PBTaskList* other);

  // implements Message ----------------------------------------------

  inline PBTaskList* New() const { return New(NULL); }

  PBTaskList* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBTaskList& from);
  void MergeFrom(const PBTaskList& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PBTaskList* other);
  void UnsafeMergeFrom(const PBTaskList& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 MaxCompleteTaskID = 1;
  void clear_maxcompletetaskid();
  static const int kMaxCompleteTaskIDFieldNumber = 1;
  ::google::protobuf::uint32 maxcompletetaskid() const;
  void set_maxcompletetaskid(::google::protobuf::uint32 value);

  // repeated fixed32 CompleteTasks = 2;
  int completetasks_size() const;
  void clear_completetasks();
  static const int kCompleteTasksFieldNumber = 2;
  ::google::protobuf::uint32 completetasks(int index) const;
  void set_completetasks(int index, ::google::protobuf::uint32 value);
  void add_completetasks(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      completetasks() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_completetasks();

  // repeated .PBTask TaskList = 3;
  int tasklist_size() const;
  void clear_tasklist();
  static const int kTaskListFieldNumber = 3;
  const ::PBTask& tasklist(int index) const;
  ::PBTask* mutable_tasklist(int index);
  ::PBTask* add_tasklist();
  ::google::protobuf::RepeatedPtrField< ::PBTask >*
      mutable_tasklist();
  const ::google::protobuf::RepeatedPtrField< ::PBTask >&
      tasklist() const;

  // @@protoc_insertion_point(class_scope:PBTaskList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > completetasks_;
  mutable int _completetasks_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::PBTask > tasklist_;
  ::google::protobuf::uint32 maxcompletetaskid_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_common_2ehxx_impl();
  friend void  protobuf_AddDesc_common_2ehxx_impl();
  friend void protobuf_AssignDesc_common_2ehxx();
  friend void protobuf_ShutdownFile_common_2ehxx();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<PBTaskList> PBTaskList_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PBItemList

// repeated .PBItemObject ItemObject = 1;
inline int PBItemList::itemobject_size() const {
  return itemobject_.size();
}
inline void PBItemList::clear_itemobject() {
  itemobject_.Clear();
}
inline const ::PBItemObject& PBItemList::itemobject(int index) const {
  // @@protoc_insertion_point(field_get:PBItemList.ItemObject)
  return itemobject_.Get(index);
}
inline ::PBItemObject* PBItemList::mutable_itemobject(int index) {
  // @@protoc_insertion_point(field_mutable:PBItemList.ItemObject)
  return itemobject_.Mutable(index);
}
inline ::PBItemObject* PBItemList::add_itemobject() {
  // @@protoc_insertion_point(field_add:PBItemList.ItemObject)
  return itemobject_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::PBItemObject >*
PBItemList::mutable_itemobject() {
  // @@protoc_insertion_point(field_mutable_list:PBItemList.ItemObject)
  return &itemobject_;
}
inline const ::google::protobuf::RepeatedPtrField< ::PBItemObject >&
PBItemList::itemobject() const {
  // @@protoc_insertion_point(field_list:PBItemList.ItemObject)
  return itemobject_;
}

// optional uint32 Size = 2;
inline void PBItemList::clear_size() {
  size_ = 0u;
}
inline ::google::protobuf::uint32 PBItemList::size() const {
  // @@protoc_insertion_point(field_get:PBItemList.Size)
  return size_;
}
inline void PBItemList::set_size(::google::protobuf::uint32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:PBItemList.Size)
}

inline const PBItemList* PBItemList::internal_default_instance() {
  return &PBItemList_default_instance_.get();
}
// -------------------------------------------------------------------

// PBItemObject

// optional uint32 ItemID = 1;
inline void PBItemObject::clear_itemid() {
  itemid_ = 0u;
}
inline ::google::protobuf::uint32 PBItemObject::itemid() const {
  // @@protoc_insertion_point(field_get:PBItemObject.ItemID)
  return itemid_;
}
inline void PBItemObject::set_itemid(::google::protobuf::uint32 value) {
  
  itemid_ = value;
  // @@protoc_insertion_point(field_set:PBItemObject.ItemID)
}

// optional uint32 Number = 2;
inline void PBItemObject::clear_number() {
  number_ = 0u;
}
inline ::google::protobuf::uint32 PBItemObject::number() const {
  // @@protoc_insertion_point(field_get:PBItemObject.Number)
  return number_;
}
inline void PBItemObject::set_number(::google::protobuf::uint32 value) {
  
  number_ = value;
  // @@protoc_insertion_point(field_set:PBItemObject.Number)
}

// optional uint32 Index = 3;
inline void PBItemObject::clear_index() {
  index_ = 0u;
}
inline ::google::protobuf::uint32 PBItemObject::index() const {
  // @@protoc_insertion_point(field_get:PBItemObject.Index)
  return index_;
}
inline void PBItemObject::set_index(::google::protobuf::uint32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:PBItemObject.Index)
}

// optional .PBItemEquip ItemEquip = 4;
inline bool PBItemObject::has_itemequip() const {
  return this != internal_default_instance() && itemequip_ != NULL;
}
inline void PBItemObject::clear_itemequip() {
  if (GetArenaNoVirtual() == NULL && itemequip_ != NULL) delete itemequip_;
  itemequip_ = NULL;
}
inline const ::PBItemEquip& PBItemObject::itemequip() const {
  // @@protoc_insertion_point(field_get:PBItemObject.ItemEquip)
  return itemequip_ != NULL ? *itemequip_
                         : *::PBItemEquip::internal_default_instance();
}
inline ::PBItemEquip* PBItemObject::mutable_itemequip() {
  
  if (itemequip_ == NULL) {
    itemequip_ = new ::PBItemEquip;
  }
  // @@protoc_insertion_point(field_mutable:PBItemObject.ItemEquip)
  return itemequip_;
}
inline ::PBItemEquip* PBItemObject::release_itemequip() {
  // @@protoc_insertion_point(field_release:PBItemObject.ItemEquip)
  
  ::PBItemEquip* temp = itemequip_;
  itemequip_ = NULL;
  return temp;
}
inline void PBItemObject::set_allocated_itemequip(::PBItemEquip* itemequip) {
  delete itemequip_;
  itemequip_ = itemequip;
  if (itemequip) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:PBItemObject.ItemEquip)
}

inline const PBItemObject* PBItemObject::internal_default_instance() {
  return &PBItemObject_default_instance_.get();
}
// -------------------------------------------------------------------

// PBItemEquip

// optional uint32 Level = 4;
inline void PBItemEquip::clear_level() {
  level_ = 0u;
}
inline ::google::protobuf::uint32 PBItemEquip::level() const {
  // @@protoc_insertion_point(field_get:PBItemEquip.Level)
  return level_;
}
inline void PBItemEquip::set_level(::google::protobuf::uint32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:PBItemEquip.Level)
}

inline const PBItemEquip* PBItemEquip::internal_default_instance() {
  return &PBItemEquip_default_instance_.get();
}
// -------------------------------------------------------------------

// PBTask

// optional uint32 TaskID = 1;
inline void PBTask::clear_taskid() {
  taskid_ = 0u;
}
inline ::google::protobuf::uint32 PBTask::taskid() const {
  // @@protoc_insertion_point(field_get:PBTask.TaskID)
  return taskid_;
}
inline void PBTask::set_taskid(::google::protobuf::uint32 value) {
  
  taskid_ = value;
  // @@protoc_insertion_point(field_set:PBTask.TaskID)
}

// repeated uint32 Param = 2;
inline int PBTask::param_size() const {
  return param_.size();
}
inline void PBTask::clear_param() {
  param_.Clear();
}
inline ::google::protobuf::uint32 PBTask::param(int index) const {
  // @@protoc_insertion_point(field_get:PBTask.Param)
  return param_.Get(index);
}
inline void PBTask::set_param(int index, ::google::protobuf::uint32 value) {
  param_.Set(index, value);
  // @@protoc_insertion_point(field_set:PBTask.Param)
}
inline void PBTask::add_param(::google::protobuf::uint32 value) {
  param_.Add(value);
  // @@protoc_insertion_point(field_add:PBTask.Param)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
PBTask::param() const {
  // @@protoc_insertion_point(field_list:PBTask.Param)
  return param_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
PBTask::mutable_param() {
  // @@protoc_insertion_point(field_mutable_list:PBTask.Param)
  return &param_;
}

// repeated uint32 CondType = 3;
inline int PBTask::condtype_size() const {
  return condtype_.size();
}
inline void PBTask::clear_condtype() {
  condtype_.Clear();
}
inline ::google::protobuf::uint32 PBTask::condtype(int index) const {
  // @@protoc_insertion_point(field_get:PBTask.CondType)
  return condtype_.Get(index);
}
inline void PBTask::set_condtype(int index, ::google::protobuf::uint32 value) {
  condtype_.Set(index, value);
  // @@protoc_insertion_point(field_set:PBTask.CondType)
}
inline void PBTask::add_condtype(::google::protobuf::uint32 value) {
  condtype_.Add(value);
  // @@protoc_insertion_point(field_add:PBTask.CondType)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
PBTask::condtype() const {
  // @@protoc_insertion_point(field_list:PBTask.CondType)
  return condtype_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
PBTask::mutable_condtype() {
  // @@protoc_insertion_point(field_mutable_list:PBTask.CondType)
  return &condtype_;
}

inline const PBTask* PBTask::internal_default_instance() {
  return &PBTask_default_instance_.get();
}
// -------------------------------------------------------------------

// PBTaskList

// optional uint32 MaxCompleteTaskID = 1;
inline void PBTaskList::clear_maxcompletetaskid() {
  maxcompletetaskid_ = 0u;
}
inline ::google::protobuf::uint32 PBTaskList::maxcompletetaskid() const {
  // @@protoc_insertion_point(field_get:PBTaskList.MaxCompleteTaskID)
  return maxcompletetaskid_;
}
inline void PBTaskList::set_maxcompletetaskid(::google::protobuf::uint32 value) {
  
  maxcompletetaskid_ = value;
  // @@protoc_insertion_point(field_set:PBTaskList.MaxCompleteTaskID)
}

// repeated fixed32 CompleteTasks = 2;
inline int PBTaskList::completetasks_size() const {
  return completetasks_.size();
}
inline void PBTaskList::clear_completetasks() {
  completetasks_.Clear();
}
inline ::google::protobuf::uint32 PBTaskList::completetasks(int index) const {
  // @@protoc_insertion_point(field_get:PBTaskList.CompleteTasks)
  return completetasks_.Get(index);
}
inline void PBTaskList::set_completetasks(int index, ::google::protobuf::uint32 value) {
  completetasks_.Set(index, value);
  // @@protoc_insertion_point(field_set:PBTaskList.CompleteTasks)
}
inline void PBTaskList::add_completetasks(::google::protobuf::uint32 value) {
  completetasks_.Add(value);
  // @@protoc_insertion_point(field_add:PBTaskList.CompleteTasks)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
PBTaskList::completetasks() const {
  // @@protoc_insertion_point(field_list:PBTaskList.CompleteTasks)
  return completetasks_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
PBTaskList::mutable_completetasks() {
  // @@protoc_insertion_point(field_mutable_list:PBTaskList.CompleteTasks)
  return &completetasks_;
}

// repeated .PBTask TaskList = 3;
inline int PBTaskList::tasklist_size() const {
  return tasklist_.size();
}
inline void PBTaskList::clear_tasklist() {
  tasklist_.Clear();
}
inline const ::PBTask& PBTaskList::tasklist(int index) const {
  // @@protoc_insertion_point(field_get:PBTaskList.TaskList)
  return tasklist_.Get(index);
}
inline ::PBTask* PBTaskList::mutable_tasklist(int index) {
  // @@protoc_insertion_point(field_mutable:PBTaskList.TaskList)
  return tasklist_.Mutable(index);
}
inline ::PBTask* PBTaskList::add_tasklist() {
  // @@protoc_insertion_point(field_add:PBTaskList.TaskList)
  return tasklist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::PBTask >*
PBTaskList::mutable_tasklist() {
  // @@protoc_insertion_point(field_mutable_list:PBTaskList.TaskList)
  return &tasklist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::PBTask >&
PBTaskList::tasklist() const {
  // @@protoc_insertion_point(field_list:PBTaskList.TaskList)
  return tasklist_;
}

inline const PBTaskList* PBTaskList::internal_default_instance() {
  return &PBTaskList_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2ehxx__INCLUDED
