// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginmessage.hxx

#ifndef PROTOBUF_loginmessage_2ehxx__INCLUDED
#define PROTOBUF_loginmessage_2ehxx__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_loginmessage_2ehxx();
void protobuf_InitDefaults_loginmessage_2ehxx();
void protobuf_AssignDesc_loginmessage_2ehxx();
void protobuf_ShutdownFile_loginmessage_2ehxx();

class CCreateRoleRequest;
class CCreateRoleResponse;
class CEnterSceneRequest;
class CEnterSceneResponse;
class CLoginRequest;
class CLoginResponse;

enum LOGIN_MODULE_MSG_ID {
  ID_LOGIN_MODULE_ERROR = 0,
  ID_C2S_REQUEST_LOGIN = 1,
  ID_S2C_RESPONSE_LOGIN = 2,
  ID_C2S_REQUEST_CREATE_ROLE = 3,
  ID_S2C_RESPONSE_CREATE_ROLE = 4,
  ID_C2S_REQUEST_ENTER_SCENE = 5,
  ID_S2C_RESPONSE_ENTER_SCENE = 6,
  LOGIN_MODULE_MSG_ID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  LOGIN_MODULE_MSG_ID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool LOGIN_MODULE_MSG_ID_IsValid(int value);
const LOGIN_MODULE_MSG_ID LOGIN_MODULE_MSG_ID_MIN = ID_LOGIN_MODULE_ERROR;
const LOGIN_MODULE_MSG_ID LOGIN_MODULE_MSG_ID_MAX = ID_S2C_RESPONSE_ENTER_SCENE;
const int LOGIN_MODULE_MSG_ID_ARRAYSIZE = LOGIN_MODULE_MSG_ID_MAX + 1;

const ::google::protobuf::EnumDescriptor* LOGIN_MODULE_MSG_ID_descriptor();
inline const ::std::string& LOGIN_MODULE_MSG_ID_Name(LOGIN_MODULE_MSG_ID value) {
  return ::google::protobuf::internal::NameOfEnum(
    LOGIN_MODULE_MSG_ID_descriptor(), value);
}
inline bool LOGIN_MODULE_MSG_ID_Parse(
    const ::std::string& name, LOGIN_MODULE_MSG_ID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LOGIN_MODULE_MSG_ID>(
    LOGIN_MODULE_MSG_ID_descriptor(), name, value);
}
// ===================================================================

class CLoginRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CLoginRequest) */ {
 public:
  CLoginRequest();
  virtual ~CLoginRequest();

  CLoginRequest(const CLoginRequest& from);

  inline CLoginRequest& operator=(const CLoginRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CLoginRequest& default_instance();

  static const CLoginRequest* internal_default_instance();

  void Swap(CLoginRequest* other);

  // implements Message ----------------------------------------------

  inline CLoginRequest* New() const { return New(NULL); }

  CLoginRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CLoginRequest& from);
  void MergeFrom(const CLoginRequest& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CLoginRequest* other);
  void UnsafeMergeFrom(const CLoginRequest& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string Name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional uint32 ChannelID = 2;
  void clear_channelid();
  static const int kChannelIDFieldNumber = 2;
  ::google::protobuf::uint32 channelid() const;
  void set_channelid(::google::protobuf::uint32 value);

  // optional uint32 ServerID = 3;
  void clear_serverid();
  static const int kServerIDFieldNumber = 3;
  ::google::protobuf::uint32 serverid() const;
  void set_serverid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CLoginRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint32 channelid_;
  ::google::protobuf::uint32 serverid_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_loginmessage_2ehxx_impl();
  friend void  protobuf_AddDesc_loginmessage_2ehxx_impl();
  friend void protobuf_AssignDesc_loginmessage_2ehxx();
  friend void protobuf_ShutdownFile_loginmessage_2ehxx();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<CLoginRequest> CLoginRequest_default_instance_;

// -------------------------------------------------------------------

class CLoginResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CLoginResponse) */ {
 public:
  CLoginResponse();
  virtual ~CLoginResponse();

  CLoginResponse(const CLoginResponse& from);

  inline CLoginResponse& operator=(const CLoginResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CLoginResponse& default_instance();

  static const CLoginResponse* internal_default_instance();

  void Swap(CLoginResponse* other);

  // implements Message ----------------------------------------------

  inline CLoginResponse* New() const { return New(NULL); }

  CLoginResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CLoginResponse& from);
  void MergeFrom(const CLoginResponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CLoginResponse* other);
  void UnsafeMergeFrom(const CLoginResponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 AccountID = 1;
  void clear_accountid();
  static const int kAccountIDFieldNumber = 1;
  ::google::protobuf::uint32 accountid() const;
  void set_accountid(::google::protobuf::uint32 value);

  // optional uint32 RoleID = 2;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 2;
  ::google::protobuf::uint32 roleid() const;
  void set_roleid(::google::protobuf::uint32 value);

  // optional uint32 ChannelID = 3;
  void clear_channelid();
  static const int kChannelIDFieldNumber = 3;
  ::google::protobuf::uint32 channelid() const;
  void set_channelid(::google::protobuf::uint32 value);

  // optional uint32 ServerID = 4;
  void clear_serverid();
  static const int kServerIDFieldNumber = 4;
  ::google::protobuf::uint32 serverid() const;
  void set_serverid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CLoginResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 accountid_;
  ::google::protobuf::uint32 roleid_;
  ::google::protobuf::uint32 channelid_;
  ::google::protobuf::uint32 serverid_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_loginmessage_2ehxx_impl();
  friend void  protobuf_AddDesc_loginmessage_2ehxx_impl();
  friend void protobuf_AssignDesc_loginmessage_2ehxx();
  friend void protobuf_ShutdownFile_loginmessage_2ehxx();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<CLoginResponse> CLoginResponse_default_instance_;

// -------------------------------------------------------------------

class CCreateRoleRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CCreateRoleRequest) */ {
 public:
  CCreateRoleRequest();
  virtual ~CCreateRoleRequest();

  CCreateRoleRequest(const CCreateRoleRequest& from);

  inline CCreateRoleRequest& operator=(const CCreateRoleRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CCreateRoleRequest& default_instance();

  static const CCreateRoleRequest* internal_default_instance();

  void Swap(CCreateRoleRequest* other);

  // implements Message ----------------------------------------------

  inline CCreateRoleRequest* New() const { return New(NULL); }

  CCreateRoleRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CCreateRoleRequest& from);
  void MergeFrom(const CCreateRoleRequest& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CCreateRoleRequest* other);
  void UnsafeMergeFrom(const CCreateRoleRequest& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 AccountID = 1;
  void clear_accountid();
  static const int kAccountIDFieldNumber = 1;
  ::google::protobuf::uint32 accountid() const;
  void set_accountid(::google::protobuf::uint32 value);

  // optional uint32 ChannelID = 2;
  void clear_channelid();
  static const int kChannelIDFieldNumber = 2;
  ::google::protobuf::uint32 channelid() const;
  void set_channelid(::google::protobuf::uint32 value);

  // optional uint32 ServerID = 3;
  void clear_serverid();
  static const int kServerIDFieldNumber = 3;
  ::google::protobuf::uint32 serverid() const;
  void set_serverid(::google::protobuf::uint32 value);

  // optional string RoleName = 4;
  void clear_rolename();
  static const int kRoleNameFieldNumber = 4;
  const ::std::string& rolename() const;
  void set_rolename(const ::std::string& value);
  void set_rolename(const char* value);
  void set_rolename(const char* value, size_t size);
  ::std::string* mutable_rolename();
  ::std::string* release_rolename();
  void set_allocated_rolename(::std::string* rolename);

  // optional uint32 Sex = 5;
  void clear_sex();
  static const int kSexFieldNumber = 5;
  ::google::protobuf::uint32 sex() const;
  void set_sex(::google::protobuf::uint32 value);

  // optional uint32 Metier = 6;
  void clear_metier();
  static const int kMetierFieldNumber = 6;
  ::google::protobuf::uint32 metier() const;
  void set_metier(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CCreateRoleRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr rolename_;
  ::google::protobuf::uint32 accountid_;
  ::google::protobuf::uint32 channelid_;
  ::google::protobuf::uint32 serverid_;
  ::google::protobuf::uint32 sex_;
  ::google::protobuf::uint32 metier_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_loginmessage_2ehxx_impl();
  friend void  protobuf_AddDesc_loginmessage_2ehxx_impl();
  friend void protobuf_AssignDesc_loginmessage_2ehxx();
  friend void protobuf_ShutdownFile_loginmessage_2ehxx();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<CCreateRoleRequest> CCreateRoleRequest_default_instance_;

// -------------------------------------------------------------------

class CCreateRoleResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CCreateRoleResponse) */ {
 public:
  CCreateRoleResponse();
  virtual ~CCreateRoleResponse();

  CCreateRoleResponse(const CCreateRoleResponse& from);

  inline CCreateRoleResponse& operator=(const CCreateRoleResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CCreateRoleResponse& default_instance();

  static const CCreateRoleResponse* internal_default_instance();

  void Swap(CCreateRoleResponse* other);

  // implements Message ----------------------------------------------

  inline CCreateRoleResponse* New() const { return New(NULL); }

  CCreateRoleResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CCreateRoleResponse& from);
  void MergeFrom(const CCreateRoleResponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CCreateRoleResponse* other);
  void UnsafeMergeFrom(const CCreateRoleResponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 Result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::uint32 result() const;
  void set_result(::google::protobuf::uint32 value);

  // optional uint32 RoleID = 2;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 2;
  ::google::protobuf::uint32 roleid() const;
  void set_roleid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CCreateRoleResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 result_;
  ::google::protobuf::uint32 roleid_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_loginmessage_2ehxx_impl();
  friend void  protobuf_AddDesc_loginmessage_2ehxx_impl();
  friend void protobuf_AssignDesc_loginmessage_2ehxx();
  friend void protobuf_ShutdownFile_loginmessage_2ehxx();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<CCreateRoleResponse> CCreateRoleResponse_default_instance_;

// -------------------------------------------------------------------

class CEnterSceneRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CEnterSceneRequest) */ {
 public:
  CEnterSceneRequest();
  virtual ~CEnterSceneRequest();

  CEnterSceneRequest(const CEnterSceneRequest& from);

  inline CEnterSceneRequest& operator=(const CEnterSceneRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CEnterSceneRequest& default_instance();

  static const CEnterSceneRequest* internal_default_instance();

  void Swap(CEnterSceneRequest* other);

  // implements Message ----------------------------------------------

  inline CEnterSceneRequest* New() const { return New(NULL); }

  CEnterSceneRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CEnterSceneRequest& from);
  void MergeFrom(const CEnterSceneRequest& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CEnterSceneRequest* other);
  void UnsafeMergeFrom(const CEnterSceneRequest& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 RoleID = 1;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  ::google::protobuf::uint32 roleid() const;
  void set_roleid(::google::protobuf::uint32 value);

  // optional uint32 AccountID = 2;
  void clear_accountid();
  static const int kAccountIDFieldNumber = 2;
  ::google::protobuf::uint32 accountid() const;
  void set_accountid(::google::protobuf::uint32 value);

  // optional uint32 ChannelID = 3;
  void clear_channelid();
  static const int kChannelIDFieldNumber = 3;
  ::google::protobuf::uint32 channelid() const;
  void set_channelid(::google::protobuf::uint32 value);

  // optional uint32 ServerID = 4;
  void clear_serverid();
  static const int kServerIDFieldNumber = 4;
  ::google::protobuf::uint32 serverid() const;
  void set_serverid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CEnterSceneRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 roleid_;
  ::google::protobuf::uint32 accountid_;
  ::google::protobuf::uint32 channelid_;
  ::google::protobuf::uint32 serverid_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_loginmessage_2ehxx_impl();
  friend void  protobuf_AddDesc_loginmessage_2ehxx_impl();
  friend void protobuf_AssignDesc_loginmessage_2ehxx();
  friend void protobuf_ShutdownFile_loginmessage_2ehxx();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<CEnterSceneRequest> CEnterSceneRequest_default_instance_;

// -------------------------------------------------------------------

class CEnterSceneResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CEnterSceneResponse) */ {
 public:
  CEnterSceneResponse();
  virtual ~CEnterSceneResponse();

  CEnterSceneResponse(const CEnterSceneResponse& from);

  inline CEnterSceneResponse& operator=(const CEnterSceneResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CEnterSceneResponse& default_instance();

  static const CEnterSceneResponse* internal_default_instance();

  void Swap(CEnterSceneResponse* other);

  // implements Message ----------------------------------------------

  inline CEnterSceneResponse* New() const { return New(NULL); }

  CEnterSceneResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CEnterSceneResponse& from);
  void MergeFrom(const CEnterSceneResponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CEnterSceneResponse* other);
  void UnsafeMergeFrom(const CEnterSceneResponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 Result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::uint32 result() const;
  void set_result(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CEnterSceneResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 result_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_loginmessage_2ehxx_impl();
  friend void  protobuf_AddDesc_loginmessage_2ehxx_impl();
  friend void protobuf_AssignDesc_loginmessage_2ehxx();
  friend void protobuf_ShutdownFile_loginmessage_2ehxx();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<CEnterSceneResponse> CEnterSceneResponse_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CLoginRequest

// optional string Name = 1;
inline void CLoginRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CLoginRequest::name() const {
  // @@protoc_insertion_point(field_get:CLoginRequest.Name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CLoginRequest::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CLoginRequest.Name)
}
inline void CLoginRequest::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CLoginRequest.Name)
}
inline void CLoginRequest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CLoginRequest.Name)
}
inline ::std::string* CLoginRequest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:CLoginRequest.Name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CLoginRequest::release_name() {
  // @@protoc_insertion_point(field_release:CLoginRequest.Name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CLoginRequest::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:CLoginRequest.Name)
}

// optional uint32 ChannelID = 2;
inline void CLoginRequest::clear_channelid() {
  channelid_ = 0u;
}
inline ::google::protobuf::uint32 CLoginRequest::channelid() const {
  // @@protoc_insertion_point(field_get:CLoginRequest.ChannelID)
  return channelid_;
}
inline void CLoginRequest::set_channelid(::google::protobuf::uint32 value) {
  
  channelid_ = value;
  // @@protoc_insertion_point(field_set:CLoginRequest.ChannelID)
}

// optional uint32 ServerID = 3;
inline void CLoginRequest::clear_serverid() {
  serverid_ = 0u;
}
inline ::google::protobuf::uint32 CLoginRequest::serverid() const {
  // @@protoc_insertion_point(field_get:CLoginRequest.ServerID)
  return serverid_;
}
inline void CLoginRequest::set_serverid(::google::protobuf::uint32 value) {
  
  serverid_ = value;
  // @@protoc_insertion_point(field_set:CLoginRequest.ServerID)
}

inline const CLoginRequest* CLoginRequest::internal_default_instance() {
  return &CLoginRequest_default_instance_.get();
}
// -------------------------------------------------------------------

// CLoginResponse

// optional uint32 AccountID = 1;
inline void CLoginResponse::clear_accountid() {
  accountid_ = 0u;
}
inline ::google::protobuf::uint32 CLoginResponse::accountid() const {
  // @@protoc_insertion_point(field_get:CLoginResponse.AccountID)
  return accountid_;
}
inline void CLoginResponse::set_accountid(::google::protobuf::uint32 value) {
  
  accountid_ = value;
  // @@protoc_insertion_point(field_set:CLoginResponse.AccountID)
}

// optional uint32 RoleID = 2;
inline void CLoginResponse::clear_roleid() {
  roleid_ = 0u;
}
inline ::google::protobuf::uint32 CLoginResponse::roleid() const {
  // @@protoc_insertion_point(field_get:CLoginResponse.RoleID)
  return roleid_;
}
inline void CLoginResponse::set_roleid(::google::protobuf::uint32 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:CLoginResponse.RoleID)
}

// optional uint32 ChannelID = 3;
inline void CLoginResponse::clear_channelid() {
  channelid_ = 0u;
}
inline ::google::protobuf::uint32 CLoginResponse::channelid() const {
  // @@protoc_insertion_point(field_get:CLoginResponse.ChannelID)
  return channelid_;
}
inline void CLoginResponse::set_channelid(::google::protobuf::uint32 value) {
  
  channelid_ = value;
  // @@protoc_insertion_point(field_set:CLoginResponse.ChannelID)
}

// optional uint32 ServerID = 4;
inline void CLoginResponse::clear_serverid() {
  serverid_ = 0u;
}
inline ::google::protobuf::uint32 CLoginResponse::serverid() const {
  // @@protoc_insertion_point(field_get:CLoginResponse.ServerID)
  return serverid_;
}
inline void CLoginResponse::set_serverid(::google::protobuf::uint32 value) {
  
  serverid_ = value;
  // @@protoc_insertion_point(field_set:CLoginResponse.ServerID)
}

inline const CLoginResponse* CLoginResponse::internal_default_instance() {
  return &CLoginResponse_default_instance_.get();
}
// -------------------------------------------------------------------

// CCreateRoleRequest

// optional uint32 AccountID = 1;
inline void CCreateRoleRequest::clear_accountid() {
  accountid_ = 0u;
}
inline ::google::protobuf::uint32 CCreateRoleRequest::accountid() const {
  // @@protoc_insertion_point(field_get:CCreateRoleRequest.AccountID)
  return accountid_;
}
inline void CCreateRoleRequest::set_accountid(::google::protobuf::uint32 value) {
  
  accountid_ = value;
  // @@protoc_insertion_point(field_set:CCreateRoleRequest.AccountID)
}

// optional uint32 ChannelID = 2;
inline void CCreateRoleRequest::clear_channelid() {
  channelid_ = 0u;
}
inline ::google::protobuf::uint32 CCreateRoleRequest::channelid() const {
  // @@protoc_insertion_point(field_get:CCreateRoleRequest.ChannelID)
  return channelid_;
}
inline void CCreateRoleRequest::set_channelid(::google::protobuf::uint32 value) {
  
  channelid_ = value;
  // @@protoc_insertion_point(field_set:CCreateRoleRequest.ChannelID)
}

// optional uint32 ServerID = 3;
inline void CCreateRoleRequest::clear_serverid() {
  serverid_ = 0u;
}
inline ::google::protobuf::uint32 CCreateRoleRequest::serverid() const {
  // @@protoc_insertion_point(field_get:CCreateRoleRequest.ServerID)
  return serverid_;
}
inline void CCreateRoleRequest::set_serverid(::google::protobuf::uint32 value) {
  
  serverid_ = value;
  // @@protoc_insertion_point(field_set:CCreateRoleRequest.ServerID)
}

// optional string RoleName = 4;
inline void CCreateRoleRequest::clear_rolename() {
  rolename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CCreateRoleRequest::rolename() const {
  // @@protoc_insertion_point(field_get:CCreateRoleRequest.RoleName)
  return rolename_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CCreateRoleRequest::set_rolename(const ::std::string& value) {
  
  rolename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CCreateRoleRequest.RoleName)
}
inline void CCreateRoleRequest::set_rolename(const char* value) {
  
  rolename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CCreateRoleRequest.RoleName)
}
inline void CCreateRoleRequest::set_rolename(const char* value, size_t size) {
  
  rolename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CCreateRoleRequest.RoleName)
}
inline ::std::string* CCreateRoleRequest::mutable_rolename() {
  
  // @@protoc_insertion_point(field_mutable:CCreateRoleRequest.RoleName)
  return rolename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CCreateRoleRequest::release_rolename() {
  // @@protoc_insertion_point(field_release:CCreateRoleRequest.RoleName)
  
  return rolename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CCreateRoleRequest::set_allocated_rolename(::std::string* rolename) {
  if (rolename != NULL) {
    
  } else {
    
  }
  rolename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), rolename);
  // @@protoc_insertion_point(field_set_allocated:CCreateRoleRequest.RoleName)
}

// optional uint32 Sex = 5;
inline void CCreateRoleRequest::clear_sex() {
  sex_ = 0u;
}
inline ::google::protobuf::uint32 CCreateRoleRequest::sex() const {
  // @@protoc_insertion_point(field_get:CCreateRoleRequest.Sex)
  return sex_;
}
inline void CCreateRoleRequest::set_sex(::google::protobuf::uint32 value) {
  
  sex_ = value;
  // @@protoc_insertion_point(field_set:CCreateRoleRequest.Sex)
}

// optional uint32 Metier = 6;
inline void CCreateRoleRequest::clear_metier() {
  metier_ = 0u;
}
inline ::google::protobuf::uint32 CCreateRoleRequest::metier() const {
  // @@protoc_insertion_point(field_get:CCreateRoleRequest.Metier)
  return metier_;
}
inline void CCreateRoleRequest::set_metier(::google::protobuf::uint32 value) {
  
  metier_ = value;
  // @@protoc_insertion_point(field_set:CCreateRoleRequest.Metier)
}

inline const CCreateRoleRequest* CCreateRoleRequest::internal_default_instance() {
  return &CCreateRoleRequest_default_instance_.get();
}
// -------------------------------------------------------------------

// CCreateRoleResponse

// optional uint32 Result = 1;
inline void CCreateRoleResponse::clear_result() {
  result_ = 0u;
}
inline ::google::protobuf::uint32 CCreateRoleResponse::result() const {
  // @@protoc_insertion_point(field_get:CCreateRoleResponse.Result)
  return result_;
}
inline void CCreateRoleResponse::set_result(::google::protobuf::uint32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:CCreateRoleResponse.Result)
}

// optional uint32 RoleID = 2;
inline void CCreateRoleResponse::clear_roleid() {
  roleid_ = 0u;
}
inline ::google::protobuf::uint32 CCreateRoleResponse::roleid() const {
  // @@protoc_insertion_point(field_get:CCreateRoleResponse.RoleID)
  return roleid_;
}
inline void CCreateRoleResponse::set_roleid(::google::protobuf::uint32 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:CCreateRoleResponse.RoleID)
}

inline const CCreateRoleResponse* CCreateRoleResponse::internal_default_instance() {
  return &CCreateRoleResponse_default_instance_.get();
}
// -------------------------------------------------------------------

// CEnterSceneRequest

// optional uint32 RoleID = 1;
inline void CEnterSceneRequest::clear_roleid() {
  roleid_ = 0u;
}
inline ::google::protobuf::uint32 CEnterSceneRequest::roleid() const {
  // @@protoc_insertion_point(field_get:CEnterSceneRequest.RoleID)
  return roleid_;
}
inline void CEnterSceneRequest::set_roleid(::google::protobuf::uint32 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:CEnterSceneRequest.RoleID)
}

// optional uint32 AccountID = 2;
inline void CEnterSceneRequest::clear_accountid() {
  accountid_ = 0u;
}
inline ::google::protobuf::uint32 CEnterSceneRequest::accountid() const {
  // @@protoc_insertion_point(field_get:CEnterSceneRequest.AccountID)
  return accountid_;
}
inline void CEnterSceneRequest::set_accountid(::google::protobuf::uint32 value) {
  
  accountid_ = value;
  // @@protoc_insertion_point(field_set:CEnterSceneRequest.AccountID)
}

// optional uint32 ChannelID = 3;
inline void CEnterSceneRequest::clear_channelid() {
  channelid_ = 0u;
}
inline ::google::protobuf::uint32 CEnterSceneRequest::channelid() const {
  // @@protoc_insertion_point(field_get:CEnterSceneRequest.ChannelID)
  return channelid_;
}
inline void CEnterSceneRequest::set_channelid(::google::protobuf::uint32 value) {
  
  channelid_ = value;
  // @@protoc_insertion_point(field_set:CEnterSceneRequest.ChannelID)
}

// optional uint32 ServerID = 4;
inline void CEnterSceneRequest::clear_serverid() {
  serverid_ = 0u;
}
inline ::google::protobuf::uint32 CEnterSceneRequest::serverid() const {
  // @@protoc_insertion_point(field_get:CEnterSceneRequest.ServerID)
  return serverid_;
}
inline void CEnterSceneRequest::set_serverid(::google::protobuf::uint32 value) {
  
  serverid_ = value;
  // @@protoc_insertion_point(field_set:CEnterSceneRequest.ServerID)
}

inline const CEnterSceneRequest* CEnterSceneRequest::internal_default_instance() {
  return &CEnterSceneRequest_default_instance_.get();
}
// -------------------------------------------------------------------

// CEnterSceneResponse

// optional uint32 Result = 1;
inline void CEnterSceneResponse::clear_result() {
  result_ = 0u;
}
inline ::google::protobuf::uint32 CEnterSceneResponse::result() const {
  // @@protoc_insertion_point(field_get:CEnterSceneResponse.Result)
  return result_;
}
inline void CEnterSceneResponse::set_result(::google::protobuf::uint32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:CEnterSceneResponse.Result)
}

inline const CEnterSceneResponse* CEnterSceneResponse::internal_default_instance() {
  return &CEnterSceneResponse_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::LOGIN_MODULE_MSG_ID> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::LOGIN_MODULE_MSG_ID>() {
  return ::LOGIN_MODULE_MSG_ID_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_loginmessage_2ehxx__INCLUDED
