// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertymodule.hxx

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "propertymodule.hxx.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* CLevelUpNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CLevelUpNotify_reflection_ = NULL;
const ::google::protobuf::Descriptor* CGMCommandRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CGMCommandRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* CGMCommandResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CGMCommandResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* CObtainExpNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CObtainExpNotify_reflection_ = NULL;
const ::google::protobuf::Descriptor* CObtainVIPExpNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CObtainVIPExpNotify_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* PROPERTY_MODULE_MSG_ID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_propertymodule_2ehxx() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_propertymodule_2ehxx() {
  protobuf_AddDesc_propertymodule_2ehxx();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "propertymodule.hxx");
  GOOGLE_CHECK(file != NULL);
  CLevelUpNotify_descriptor_ = file->message_type(0);
  static const int CLevelUpNotify_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CLevelUpNotify, level_),
  };
  CLevelUpNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CLevelUpNotify_descriptor_,
      CLevelUpNotify::internal_default_instance(),
      CLevelUpNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(CLevelUpNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CLevelUpNotify, _internal_metadata_));
  CGMCommandRequest_descriptor_ = file->message_type(1);
  static const int CGMCommandRequest_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CGMCommandRequest, commandstring_),
  };
  CGMCommandRequest_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CGMCommandRequest_descriptor_,
      CGMCommandRequest::internal_default_instance(),
      CGMCommandRequest_offsets_,
      -1,
      -1,
      -1,
      sizeof(CGMCommandRequest),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CGMCommandRequest, _internal_metadata_));
  CGMCommandResponse_descriptor_ = file->message_type(2);
  static const int CGMCommandResponse_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CGMCommandResponse, result_),
  };
  CGMCommandResponse_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CGMCommandResponse_descriptor_,
      CGMCommandResponse::internal_default_instance(),
      CGMCommandResponse_offsets_,
      -1,
      -1,
      -1,
      sizeof(CGMCommandResponse),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CGMCommandResponse, _internal_metadata_));
  CObtainExpNotify_descriptor_ = file->message_type(3);
  static const int CObtainExpNotify_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CObtainExpNotify, exp_),
  };
  CObtainExpNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CObtainExpNotify_descriptor_,
      CObtainExpNotify::internal_default_instance(),
      CObtainExpNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(CObtainExpNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CObtainExpNotify, _internal_metadata_));
  CObtainVIPExpNotify_descriptor_ = file->message_type(4);
  static const int CObtainVIPExpNotify_offsets_[1] = {
  };
  CObtainVIPExpNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CObtainVIPExpNotify_descriptor_,
      CObtainVIPExpNotify::internal_default_instance(),
      CObtainVIPExpNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(CObtainVIPExpNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CObtainVIPExpNotify, _internal_metadata_));
  PROPERTY_MODULE_MSG_ID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_propertymodule_2ehxx);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CLevelUpNotify_descriptor_, CLevelUpNotify::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CGMCommandRequest_descriptor_, CGMCommandRequest::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CGMCommandResponse_descriptor_, CGMCommandResponse::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CObtainExpNotify_descriptor_, CObtainExpNotify::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CObtainVIPExpNotify_descriptor_, CObtainVIPExpNotify::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_propertymodule_2ehxx() {
  CLevelUpNotify_default_instance_.Shutdown();
  delete CLevelUpNotify_reflection_;
  CGMCommandRequest_default_instance_.Shutdown();
  delete CGMCommandRequest_reflection_;
  CGMCommandResponse_default_instance_.Shutdown();
  delete CGMCommandResponse_reflection_;
  CObtainExpNotify_default_instance_.Shutdown();
  delete CObtainExpNotify_reflection_;
  CObtainVIPExpNotify_default_instance_.Shutdown();
  delete CObtainVIPExpNotify_reflection_;
}

void protobuf_InitDefaults_propertymodule_2ehxx_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  CLevelUpNotify_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  CGMCommandRequest_default_instance_.DefaultConstruct();
  CGMCommandResponse_default_instance_.DefaultConstruct();
  CObtainExpNotify_default_instance_.DefaultConstruct();
  CObtainVIPExpNotify_default_instance_.DefaultConstruct();
  CLevelUpNotify_default_instance_.get_mutable()->InitAsDefaultInstance();
  CGMCommandRequest_default_instance_.get_mutable()->InitAsDefaultInstance();
  CGMCommandResponse_default_instance_.get_mutable()->InitAsDefaultInstance();
  CObtainExpNotify_default_instance_.get_mutable()->InitAsDefaultInstance();
  CObtainVIPExpNotify_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_propertymodule_2ehxx_once_);
void protobuf_InitDefaults_propertymodule_2ehxx() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_propertymodule_2ehxx_once_,
                 &protobuf_InitDefaults_propertymodule_2ehxx_impl);
}
void protobuf_AddDesc_propertymodule_2ehxx_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_propertymodule_2ehxx();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022propertymodule.hxx\"\037\n\016CLevelUpNotify\022\r"
    "\n\005Level\030\001 \001(\r\"*\n\021CGMCommandRequest\022\025\n\rCo"
    "mmandString\030\001 \001(\t\"$\n\022CGMCommandResponse\022"
    "\016\n\006Result\030\001 \001(\r\"\037\n\020CObtainExpNotify\022\013\n\003E"
    "xp\030\001 \001(\r\"\025\n\023CObtainVIPExpNotify*\224\001\n\026PROP"
    "ERTY_MODULE_MSG_ID\022\034\n\030ID_PROPERTY_MODULE"
    "_ERROR\020\000\022\033\n\026ID_S2C_NOTIYF_LEVEL_UP\020\200\010\022\036\n"
    "\031ID_C2S_REQUEST_GM_COMMAND\020\201\010\022\037\n\032ID_S2C_"
    "RESPONSE_GM_COMMAND\020\202\010b\006proto3", 350);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "propertymodule.hxx", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_propertymodule_2ehxx);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_propertymodule_2ehxx_once_);
void protobuf_AddDesc_propertymodule_2ehxx() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_propertymodule_2ehxx_once_,
                 &protobuf_AddDesc_propertymodule_2ehxx_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_propertymodule_2ehxx {
  StaticDescriptorInitializer_propertymodule_2ehxx() {
    protobuf_AddDesc_propertymodule_2ehxx();
  }
} static_descriptor_initializer_propertymodule_2ehxx_;
const ::google::protobuf::EnumDescriptor* PROPERTY_MODULE_MSG_ID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PROPERTY_MODULE_MSG_ID_descriptor_;
}
bool PROPERTY_MODULE_MSG_ID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1024:
    case 1025:
    case 1026:
      return true;
    default:
      return false;
  }
}


namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CLevelUpNotify::kLevelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CLevelUpNotify::CLevelUpNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_propertymodule_2ehxx();
  SharedCtor();
  // @@protoc_insertion_point(constructor:CLevelUpNotify)
}

void CLevelUpNotify::InitAsDefaultInstance() {
}

CLevelUpNotify::CLevelUpNotify(const CLevelUpNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CLevelUpNotify)
}

void CLevelUpNotify::SharedCtor() {
  level_ = 0u;
  _cached_size_ = 0;
}

CLevelUpNotify::~CLevelUpNotify() {
  // @@protoc_insertion_point(destructor:CLevelUpNotify)
  SharedDtor();
}

void CLevelUpNotify::SharedDtor() {
}

void CLevelUpNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CLevelUpNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CLevelUpNotify_descriptor_;
}

const CLevelUpNotify& CLevelUpNotify::default_instance() {
  protobuf_InitDefaults_propertymodule_2ehxx();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<CLevelUpNotify> CLevelUpNotify_default_instance_;

CLevelUpNotify* CLevelUpNotify::New(::google::protobuf::Arena* arena) const {
  CLevelUpNotify* n = new CLevelUpNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CLevelUpNotify::Clear() {
// @@protoc_insertion_point(message_clear_start:CLevelUpNotify)
  level_ = 0u;
}

bool CLevelUpNotify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CLevelUpNotify)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 Level = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &level_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CLevelUpNotify)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CLevelUpNotify)
  return false;
#undef DO_
}

void CLevelUpNotify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CLevelUpNotify)
  // optional uint32 Level = 1;
  if (this->level() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->level(), output);
  }

  // @@protoc_insertion_point(serialize_end:CLevelUpNotify)
}

::google::protobuf::uint8* CLevelUpNotify::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CLevelUpNotify)
  // optional uint32 Level = 1;
  if (this->level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->level(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:CLevelUpNotify)
  return target;
}

size_t CLevelUpNotify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CLevelUpNotify)
  size_t total_size = 0;

  // optional uint32 Level = 1;
  if (this->level() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->level());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CLevelUpNotify::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CLevelUpNotify)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CLevelUpNotify* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CLevelUpNotify>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CLevelUpNotify)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CLevelUpNotify)
    UnsafeMergeFrom(*source);
  }
}

void CLevelUpNotify::MergeFrom(const CLevelUpNotify& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CLevelUpNotify)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void CLevelUpNotify::UnsafeMergeFrom(const CLevelUpNotify& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.level() != 0) {
    set_level(from.level());
  }
}

void CLevelUpNotify::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CLevelUpNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CLevelUpNotify::CopyFrom(const CLevelUpNotify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CLevelUpNotify)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool CLevelUpNotify::IsInitialized() const {

  return true;
}

void CLevelUpNotify::Swap(CLevelUpNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CLevelUpNotify::InternalSwap(CLevelUpNotify* other) {
  std::swap(level_, other->level_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CLevelUpNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CLevelUpNotify_descriptor_;
  metadata.reflection = CLevelUpNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CLevelUpNotify

// optional uint32 Level = 1;
void CLevelUpNotify::clear_level() {
  level_ = 0u;
}
::google::protobuf::uint32 CLevelUpNotify::level() const {
  // @@protoc_insertion_point(field_get:CLevelUpNotify.Level)
  return level_;
}
void CLevelUpNotify::set_level(::google::protobuf::uint32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:CLevelUpNotify.Level)
}

inline const CLevelUpNotify* CLevelUpNotify::internal_default_instance() {
  return &CLevelUpNotify_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CGMCommandRequest::kCommandStringFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CGMCommandRequest::CGMCommandRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_propertymodule_2ehxx();
  SharedCtor();
  // @@protoc_insertion_point(constructor:CGMCommandRequest)
}

void CGMCommandRequest::InitAsDefaultInstance() {
}

CGMCommandRequest::CGMCommandRequest(const CGMCommandRequest& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CGMCommandRequest)
}

void CGMCommandRequest::SharedCtor() {
  commandstring_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

CGMCommandRequest::~CGMCommandRequest() {
  // @@protoc_insertion_point(destructor:CGMCommandRequest)
  SharedDtor();
}

void CGMCommandRequest::SharedDtor() {
  commandstring_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CGMCommandRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CGMCommandRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CGMCommandRequest_descriptor_;
}

const CGMCommandRequest& CGMCommandRequest::default_instance() {
  protobuf_InitDefaults_propertymodule_2ehxx();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<CGMCommandRequest> CGMCommandRequest_default_instance_;

CGMCommandRequest* CGMCommandRequest::New(::google::protobuf::Arena* arena) const {
  CGMCommandRequest* n = new CGMCommandRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CGMCommandRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:CGMCommandRequest)
  commandstring_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool CGMCommandRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CGMCommandRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string CommandString = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_commandstring()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->commandstring().data(), this->commandstring().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "CGMCommandRequest.CommandString"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CGMCommandRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CGMCommandRequest)
  return false;
#undef DO_
}

void CGMCommandRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CGMCommandRequest)
  // optional string CommandString = 1;
  if (this->commandstring().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->commandstring().data(), this->commandstring().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CGMCommandRequest.CommandString");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->commandstring(), output);
  }

  // @@protoc_insertion_point(serialize_end:CGMCommandRequest)
}

::google::protobuf::uint8* CGMCommandRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CGMCommandRequest)
  // optional string CommandString = 1;
  if (this->commandstring().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->commandstring().data(), this->commandstring().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "CGMCommandRequest.CommandString");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->commandstring(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:CGMCommandRequest)
  return target;
}

size_t CGMCommandRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CGMCommandRequest)
  size_t total_size = 0;

  // optional string CommandString = 1;
  if (this->commandstring().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->commandstring());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CGMCommandRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CGMCommandRequest)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CGMCommandRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CGMCommandRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CGMCommandRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CGMCommandRequest)
    UnsafeMergeFrom(*source);
  }
}

void CGMCommandRequest::MergeFrom(const CGMCommandRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CGMCommandRequest)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void CGMCommandRequest::UnsafeMergeFrom(const CGMCommandRequest& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.commandstring().size() > 0) {

    commandstring_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.commandstring_);
  }
}

void CGMCommandRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CGMCommandRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CGMCommandRequest::CopyFrom(const CGMCommandRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CGMCommandRequest)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool CGMCommandRequest::IsInitialized() const {

  return true;
}

void CGMCommandRequest::Swap(CGMCommandRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CGMCommandRequest::InternalSwap(CGMCommandRequest* other) {
  commandstring_.Swap(&other->commandstring_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CGMCommandRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CGMCommandRequest_descriptor_;
  metadata.reflection = CGMCommandRequest_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CGMCommandRequest

// optional string CommandString = 1;
void CGMCommandRequest::clear_commandstring() {
  commandstring_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CGMCommandRequest::commandstring() const {
  // @@protoc_insertion_point(field_get:CGMCommandRequest.CommandString)
  return commandstring_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CGMCommandRequest::set_commandstring(const ::std::string& value) {
  
  commandstring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CGMCommandRequest.CommandString)
}
void CGMCommandRequest::set_commandstring(const char* value) {
  
  commandstring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CGMCommandRequest.CommandString)
}
void CGMCommandRequest::set_commandstring(const char* value, size_t size) {
  
  commandstring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CGMCommandRequest.CommandString)
}
::std::string* CGMCommandRequest::mutable_commandstring() {
  
  // @@protoc_insertion_point(field_mutable:CGMCommandRequest.CommandString)
  return commandstring_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CGMCommandRequest::release_commandstring() {
  // @@protoc_insertion_point(field_release:CGMCommandRequest.CommandString)
  
  return commandstring_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CGMCommandRequest::set_allocated_commandstring(::std::string* commandstring) {
  if (commandstring != NULL) {
    
  } else {
    
  }
  commandstring_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), commandstring);
  // @@protoc_insertion_point(field_set_allocated:CGMCommandRequest.CommandString)
}

inline const CGMCommandRequest* CGMCommandRequest::internal_default_instance() {
  return &CGMCommandRequest_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CGMCommandResponse::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CGMCommandResponse::CGMCommandResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_propertymodule_2ehxx();
  SharedCtor();
  // @@protoc_insertion_point(constructor:CGMCommandResponse)
}

void CGMCommandResponse::InitAsDefaultInstance() {
}

CGMCommandResponse::CGMCommandResponse(const CGMCommandResponse& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CGMCommandResponse)
}

void CGMCommandResponse::SharedCtor() {
  result_ = 0u;
  _cached_size_ = 0;
}

CGMCommandResponse::~CGMCommandResponse() {
  // @@protoc_insertion_point(destructor:CGMCommandResponse)
  SharedDtor();
}

void CGMCommandResponse::SharedDtor() {
}

void CGMCommandResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CGMCommandResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CGMCommandResponse_descriptor_;
}

const CGMCommandResponse& CGMCommandResponse::default_instance() {
  protobuf_InitDefaults_propertymodule_2ehxx();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<CGMCommandResponse> CGMCommandResponse_default_instance_;

CGMCommandResponse* CGMCommandResponse::New(::google::protobuf::Arena* arena) const {
  CGMCommandResponse* n = new CGMCommandResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CGMCommandResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:CGMCommandResponse)
  result_ = 0u;
}

bool CGMCommandResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CGMCommandResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 Result = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &result_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CGMCommandResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CGMCommandResponse)
  return false;
#undef DO_
}

void CGMCommandResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CGMCommandResponse)
  // optional uint32 Result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->result(), output);
  }

  // @@protoc_insertion_point(serialize_end:CGMCommandResponse)
}

::google::protobuf::uint8* CGMCommandResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CGMCommandResponse)
  // optional uint32 Result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->result(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:CGMCommandResponse)
  return target;
}

size_t CGMCommandResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CGMCommandResponse)
  size_t total_size = 0;

  // optional uint32 Result = 1;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->result());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CGMCommandResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CGMCommandResponse)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CGMCommandResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CGMCommandResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CGMCommandResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CGMCommandResponse)
    UnsafeMergeFrom(*source);
  }
}

void CGMCommandResponse::MergeFrom(const CGMCommandResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CGMCommandResponse)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void CGMCommandResponse::UnsafeMergeFrom(const CGMCommandResponse& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.result() != 0) {
    set_result(from.result());
  }
}

void CGMCommandResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CGMCommandResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CGMCommandResponse::CopyFrom(const CGMCommandResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CGMCommandResponse)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool CGMCommandResponse::IsInitialized() const {

  return true;
}

void CGMCommandResponse::Swap(CGMCommandResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CGMCommandResponse::InternalSwap(CGMCommandResponse* other) {
  std::swap(result_, other->result_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CGMCommandResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CGMCommandResponse_descriptor_;
  metadata.reflection = CGMCommandResponse_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CGMCommandResponse

// optional uint32 Result = 1;
void CGMCommandResponse::clear_result() {
  result_ = 0u;
}
::google::protobuf::uint32 CGMCommandResponse::result() const {
  // @@protoc_insertion_point(field_get:CGMCommandResponse.Result)
  return result_;
}
void CGMCommandResponse::set_result(::google::protobuf::uint32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:CGMCommandResponse.Result)
}

inline const CGMCommandResponse* CGMCommandResponse::internal_default_instance() {
  return &CGMCommandResponse_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CObtainExpNotify::kExpFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CObtainExpNotify::CObtainExpNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_propertymodule_2ehxx();
  SharedCtor();
  // @@protoc_insertion_point(constructor:CObtainExpNotify)
}

void CObtainExpNotify::InitAsDefaultInstance() {
}

CObtainExpNotify::CObtainExpNotify(const CObtainExpNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CObtainExpNotify)
}

void CObtainExpNotify::SharedCtor() {
  exp_ = 0u;
  _cached_size_ = 0;
}

CObtainExpNotify::~CObtainExpNotify() {
  // @@protoc_insertion_point(destructor:CObtainExpNotify)
  SharedDtor();
}

void CObtainExpNotify::SharedDtor() {
}

void CObtainExpNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CObtainExpNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CObtainExpNotify_descriptor_;
}

const CObtainExpNotify& CObtainExpNotify::default_instance() {
  protobuf_InitDefaults_propertymodule_2ehxx();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<CObtainExpNotify> CObtainExpNotify_default_instance_;

CObtainExpNotify* CObtainExpNotify::New(::google::protobuf::Arena* arena) const {
  CObtainExpNotify* n = new CObtainExpNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CObtainExpNotify::Clear() {
// @@protoc_insertion_point(message_clear_start:CObtainExpNotify)
  exp_ = 0u;
}

bool CObtainExpNotify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CObtainExpNotify)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 Exp = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &exp_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CObtainExpNotify)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CObtainExpNotify)
  return false;
#undef DO_
}

void CObtainExpNotify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CObtainExpNotify)
  // optional uint32 Exp = 1;
  if (this->exp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->exp(), output);
  }

  // @@protoc_insertion_point(serialize_end:CObtainExpNotify)
}

::google::protobuf::uint8* CObtainExpNotify::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CObtainExpNotify)
  // optional uint32 Exp = 1;
  if (this->exp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->exp(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:CObtainExpNotify)
  return target;
}

size_t CObtainExpNotify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CObtainExpNotify)
  size_t total_size = 0;

  // optional uint32 Exp = 1;
  if (this->exp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->exp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CObtainExpNotify::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CObtainExpNotify)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CObtainExpNotify* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CObtainExpNotify>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CObtainExpNotify)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CObtainExpNotify)
    UnsafeMergeFrom(*source);
  }
}

void CObtainExpNotify::MergeFrom(const CObtainExpNotify& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CObtainExpNotify)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void CObtainExpNotify::UnsafeMergeFrom(const CObtainExpNotify& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.exp() != 0) {
    set_exp(from.exp());
  }
}

void CObtainExpNotify::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CObtainExpNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CObtainExpNotify::CopyFrom(const CObtainExpNotify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CObtainExpNotify)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool CObtainExpNotify::IsInitialized() const {

  return true;
}

void CObtainExpNotify::Swap(CObtainExpNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CObtainExpNotify::InternalSwap(CObtainExpNotify* other) {
  std::swap(exp_, other->exp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CObtainExpNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CObtainExpNotify_descriptor_;
  metadata.reflection = CObtainExpNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CObtainExpNotify

// optional uint32 Exp = 1;
void CObtainExpNotify::clear_exp() {
  exp_ = 0u;
}
::google::protobuf::uint32 CObtainExpNotify::exp() const {
  // @@protoc_insertion_point(field_get:CObtainExpNotify.Exp)
  return exp_;
}
void CObtainExpNotify::set_exp(::google::protobuf::uint32 value) {
  
  exp_ = value;
  // @@protoc_insertion_point(field_set:CObtainExpNotify.Exp)
}

inline const CObtainExpNotify* CObtainExpNotify::internal_default_instance() {
  return &CObtainExpNotify_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CObtainVIPExpNotify::CObtainVIPExpNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_propertymodule_2ehxx();
  SharedCtor();
  // @@protoc_insertion_point(constructor:CObtainVIPExpNotify)
}

void CObtainVIPExpNotify::InitAsDefaultInstance() {
}

CObtainVIPExpNotify::CObtainVIPExpNotify(const CObtainVIPExpNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CObtainVIPExpNotify)
}

void CObtainVIPExpNotify::SharedCtor() {
  _cached_size_ = 0;
}

CObtainVIPExpNotify::~CObtainVIPExpNotify() {
  // @@protoc_insertion_point(destructor:CObtainVIPExpNotify)
  SharedDtor();
}

void CObtainVIPExpNotify::SharedDtor() {
}

void CObtainVIPExpNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CObtainVIPExpNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CObtainVIPExpNotify_descriptor_;
}

const CObtainVIPExpNotify& CObtainVIPExpNotify::default_instance() {
  protobuf_InitDefaults_propertymodule_2ehxx();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<CObtainVIPExpNotify> CObtainVIPExpNotify_default_instance_;

CObtainVIPExpNotify* CObtainVIPExpNotify::New(::google::protobuf::Arena* arena) const {
  CObtainVIPExpNotify* n = new CObtainVIPExpNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CObtainVIPExpNotify::Clear() {
// @@protoc_insertion_point(message_clear_start:CObtainVIPExpNotify)
}

bool CObtainVIPExpNotify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CObtainVIPExpNotify)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:CObtainVIPExpNotify)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CObtainVIPExpNotify)
  return false;
#undef DO_
}

void CObtainVIPExpNotify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CObtainVIPExpNotify)
  // @@protoc_insertion_point(serialize_end:CObtainVIPExpNotify)
}

::google::protobuf::uint8* CObtainVIPExpNotify::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CObtainVIPExpNotify)
  // @@protoc_insertion_point(serialize_to_array_end:CObtainVIPExpNotify)
  return target;
}

size_t CObtainVIPExpNotify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CObtainVIPExpNotify)
  size_t total_size = 0;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CObtainVIPExpNotify::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CObtainVIPExpNotify)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CObtainVIPExpNotify* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CObtainVIPExpNotify>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CObtainVIPExpNotify)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CObtainVIPExpNotify)
    UnsafeMergeFrom(*source);
  }
}

void CObtainVIPExpNotify::MergeFrom(const CObtainVIPExpNotify& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CObtainVIPExpNotify)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void CObtainVIPExpNotify::UnsafeMergeFrom(const CObtainVIPExpNotify& from) {
  GOOGLE_DCHECK(&from != this);
}

void CObtainVIPExpNotify::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CObtainVIPExpNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CObtainVIPExpNotify::CopyFrom(const CObtainVIPExpNotify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CObtainVIPExpNotify)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool CObtainVIPExpNotify::IsInitialized() const {

  return true;
}

void CObtainVIPExpNotify::Swap(CObtainVIPExpNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CObtainVIPExpNotify::InternalSwap(CObtainVIPExpNotify* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CObtainVIPExpNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CObtainVIPExpNotify_descriptor_;
  metadata.reflection = CObtainVIPExpNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CObtainVIPExpNotify

inline const CObtainVIPExpNotify* CObtainVIPExpNotify::internal_default_instance() {
  return &CObtainVIPExpNotify_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
